include ../../makefile.inc

.PHONY: all clean


ifdef ESOCKET
iam="I am defined"
else
iam="I am not defined"
endif

all:
	@echo "esocket make. $(ESOCKET)"
	@echo $(iam) 
	@pwd

clean:
	@echo "esocket clean"

